name: CI Node.Js

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"] 
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Repository
      uses: actions/checkout@v2
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Dependencies
      run: npm i
    
    - name: Start the Application and Capture the output
      run: |
        OUTPUT:$(node src/index.js)
        echo "::set-output name=output::$OUTPUT"
        echo "$OUTPUT"
    
    - name: Verify output
      run: |
        echo "Output captured in previous step: ${{ steps.start.outputs.output }}"

